WITH ORDERS_COUNT AS (
    SELECT
        C.CUSTOMERID CUSTOMERID,
        C.FIRSTNAME FIRSTNAME,
        COUNT(O.ORDERID) AS TOTAL_ORDERS
    FROM
        ECOM_DB.L1_LANDING.CUSTOMERS C
        LEFT JOIN ECOM_DB.L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY
        C.CUSTOMERID,
        C.FIRSTNAME
    ORDER BY
    
        TOTAL_ORDERS DESC
)
SELECT
    *
FROM
    ORDERS_COUNT